# Generated by Django 6.1.1 on 2026-09-13 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pickup_point_address',
            field=models.CharField(default='bla', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='order',
            name='pickup_point_id',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
    ]
