# Generated by Django 6.1.1 on 2026-09-09 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0002_order_stripe_checkout_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pickup_point_id',
            field=models.IntegerField(null=True),
        ),
    ]
