# Generated by Django 6.1.1 on 2026-09-15 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0003_remove_order_address_remove_order_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pickup_point_id',
            field=models.CharField(max_length=16),
        ),
    ]
