# Generated by Django 6.1.1 on 2026-09-20 07:43

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0007_orderitem_vat_rate_product_vat_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_vat_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('23.00'), max_digits=4),
        ),
    ]
