# Generated by Django 6.1.1 on 2026-09-20 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0008_order_delivery_fee_order_delivery_vat_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_shipping',
            field=models.BooleanField(default=False),
        ),
    ]
