# Generated by Django 6.1.1 on 2026-09-20 11:29

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0010_seed_shipping_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='vat_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('5.00'), max_digits=4),
        ),
        migrations.AlterField(
            model_name='product',
            name='vat_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('5.00'), help_text='VAT rate in percent, e.g. 23.00 (standard) or 5.00 (books)', max_digits=4),
        ),
    ]
