# Generated by Django 6.1.1 on 2026-09-20 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0011_alter_orderitem_vat_rate_alter_product_vat_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('book', 'Book'), ('merch', 'Merch')], default='book', max_length=20),
        ),
        migrations.CreateModel(
            name='BookDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(blank=True, max_length=20)),
                ('page_count', models.PositiveIntegerField(blank=True, null=True)),
                ('binding', models.CharField(blank=True, choices=[('hardcover', 'Viazaná'), ('paperback', 'Brožovaná')], max_length=20)),
                ('dimensions', models.CharField(blank=True, help_text='e.g. 210 × 148 × 20 mm', max_length=50)),
                ('language', models.CharField(blank=True, max_length=50)),
                ('publisher', models.CharField(blank=True, max_length=200)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='book_details', to='eshop.product')),
            ],
        ),
        migrations.CreateModel(
            name='MerchDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(blank=True, max_length=50)),
                ('color', models.CharField(blank=True, max_length=50)),
                ('material', models.CharField(blank=True, max_length=100)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='merch_details', to='eshop.product')),
            ],
        ),
    ]
