# Generated by Django 6.1.1 on 2026-09-20 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0012_product_category_bookdetails_merchdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookdetails',
            name='language',
            field=models.CharField(blank=True, default='Slovenský', max_length=50),
        ),
        migrations.AlterField(
            model_name='bookdetails',
            name='publisher',
            field=models.CharField(blank=True, default='PK Bytes', max_length=200),
        ),
    ]
