# Generated by Django 6.1.1 on 2026-09-20 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0013_alter_bookdetails_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookdetails',
            name='weight',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bookdetails',
            name='binding',
            field=models.CharField(blank=True, choices=[('hardcover', 'Pevná väzba'), ('paperback', 'Brožovaná väzba')], max_length=20),
        ),
    ]
