# Generated by Django 6.1.1 on 2026-09-20 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0014_bookdetails_weight_alter_bookdetails_binding'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookdetails',
            name='published_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bookdetails',
            name='weight',
            field=models.PositiveIntegerField(blank=True, help_text='grams', null=True),
        ),
    ]
