# Generated by Django 6.1.1 on 2026-09-27 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0015_bookdetails_published_at_alter_bookdetails_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookdetails',
            name='binding',
            field=models.CharField(blank=True, choices=[('hardcover', 'Pevná'), ('paperback', 'Brožovaná')], max_length=20),
        ),
    ]
