# Generated by Django 6.1.1 on 2026-10-01 00:00

from django.db import migrations, models


def set_type_from_is_shipping(apps, schema_editor):
    Product = apps.get_model("eshop", "Product")
    Product.objects.filter(is_shipping=True).update(type="doprava")


def set_is_shipping_from_type(apps, schema_editor):
    Product = apps.get_model("eshop", "Product")
    Product.objects.filter(type="doprava").update(is_shipping=True)


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0017_order_billing_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('kniha', 'Kniha'), ('doprava', 'Doprava')], default='kniha', max_length=20),
        ),
        migrations.RunPython(set_type_from_is_shipping, set_is_shipping_from_type),
        migrations.RemoveField(
            model_name='product',
            name='is_shipping',
        ),
    ]
