# Generated by Django 6.1.1 on 2026-10-01 00:00

from django.db import migrations, models


def set_category_from_type(apps, schema_editor):
    Product = apps.get_model("eshop", "Product")
    Product.objects.filter(type="doprava").update(category="shipping")


def set_type_from_category(apps, schema_editor):
    Product = apps.get_model("eshop", "Product")
    Product.objects.filter(category="shipping").update(type="doprava")


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0018_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(
                choices=[('book', 'Kniha'), ('merch', 'Merch'), ('shipping', 'Doprava')],
                default='book',
                max_length=20,
            ),
        ),
        migrations.RunPython(set_category_from_type, set_type_from_category),
        migrations.RemoveField(
            model_name='product',
            name='type',
        ),
    ]
